export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SET_PEDIDO = "SET_PEDIDO";
export const PEDIDO_REQUEST = "PEDIDO_REQUEST";
export const PEDIDO_SUCCESS = "PEDIDO_SUCCESS";
export const PEDIDO_FAILURE = "PEDIDO_FAILURE";

export const SAVE_PEDIDO_REQUEST = "SAVE_PEDIDO_REQUEST";
export const SAVE_PEDIDO_SUCCESS = "SAVE_PEDIDO_SUCCESS";
export const SAVE_PEDIDO_FAILURE = "SAVE_PEDIDO_FAILURE";
